spring:
  application:
    name: report
  ai:
    openai:
      api-key: ENC(5Ukc8oP4SHi4uTslZPLQEl7AeLOCZBG3MkTOUYejmmX7Az3Q+tgFcqtJ+iapz3CLLlw++dzZX0Mqac4wGFIbjDjy9IgeR7Ji69AZ5dA+yuNisj72ySWCoUO+hI7WVQD3AomzMKlk4r3Lcwpp0ZTuACrXXq8N6177hliS3ZxWWMSIphES9AoVPiTBiOwn1tvdW7yDUPJPKKpBDD+6LALNBBVkIhnASnyGAuKsxvTyIDc=)
      chat:
        enabled: true
        options:
          model: gpt-4-turbo
          maxCompletionTokens : 2048

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

report:
  openai:
    template: "{portfolio} 위의 내 포트폴리오인데 tossPortfolioDTO는 내 주식 포트폴리오이고, kbPortfolioDTO는 내 펀드 포트폴리오야. 둘다 보고 주요 종목별 경제 뉴스 제공, 포트폴리오 리밸런싱 조언, 추가 매수/매도 전략 추천해줘. markDown으로 작성해주고 가시성 좋게 항목별로 확실하고 다양하게 헤더(Header), 폰트, 목록, 인용문 수평선 넣기, 문단 나누기를 사용하고 구분해서 markDown을 작성하고 주요 챕터, 제목마다 아이콘도 이쁘게 달아서 작성"

kb:
  id: ENC(ecGpJSU3v18shsYaCcp8eA==)
  password: ENC(uO6VgHReKQ8FYOrRMj9zqSipNsOa7dVXMl9EdFbylhU=)

toss:
  id: ENC(OLm9iKuN9xCNUoyFyFUIQUQbF7xpLLc9)
  birthDay: ENC(j0nmhwmVKjfUGgQwCVmcfg==)
  phoneNumber: ENC(+Qrzsn++O0uPlhZo0mIIEF24qrNiiriW)

---
spring:
  config:
    activate:
      on-profile: "local"

chrome:
  auth: ENC(GMnuV8Ih9PrTlfmgDJqcAexOq1FhoWniSpYAdX4AogMIX517IwTZrEaZ3OMRfX6w)

---
spring:
  config:
    activate:
      on-profile: "prod"

chrome:
  auth: ENC(HdSeuFgwAFFqdu5o8G/RrXPhF98Z4Nx9exX0ldTwJwOj9+vzBE32sQ==)